# Generated by Django 5.0.6 on 2024-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projects_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
